export const UPDATE_SEARCH_BAR = 'UPDATE_SEARCH_BAR';

export const UPDATE_DATE_FROM = 'UPDATE_DATE_FROM';
export const UPDATE_DATE_TO = 'UPDATE_DATE_TO';
export const UPDATE_GENRES = 'UPDATE_GENRES';

export const UPDATE_QUERY_LIST = 'UPDATE_QUERY_LIST';

export const FETCH_MOVIE_RESULTS = 'FETCH_MOVIE_RESULTS';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';


export const SET_LAST_PARAMS = 'SET_LAST_PARAMS';

export const INC_PAGE = 'INC_PAGE';
export const DEC_PAGE = 'DEC_PAGE';

